menu_options:
 - "select"
 - "station info"
 - "train schedule"
 - "all trains from station"
 - "train fares"
 - "seat availability"

script_menu:
 - station name to code
 - train number to name
 - train name to number
 