menu_options:
 - "select"
 - "station info"
 - "train schedule"
 - "all trains from station"
 - "train fares"
 - "seat availability"
 - "speacial trains"
 - "premium trains"

script_menu:
 - station name to code
 - train number to name

 