menu_options:
 - "select"
 - "station info"
 - "train schedule"
 - "all trains from station"
 - "train fares"
 - "seat availability"


special_trains:
 - "special train"
 - "premium trains"
 - "rajdhani trains"


script_menu:
 - station name to code
 - train number to name

 